version: '3.3'

services:
  
  # PHP
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src/:/var/www/html

  # Nginx
  web:
    container_name: laravel_web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile

    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile

    ports:
      - ${DB_PORT}:3306
    # MySQLの環境変数
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: user
      MYSQL_PASSWORD: passs
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  #Myadmin
  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOSTS=mysql
      ports:
        - "3000:80"
      volumes:
        - ./docker/phpmyadmin/sessions:/sessions